openapi: 3.0.0
info:
  contact:
    email: jevans97@utk.edu
  description: "Provides various methods for retrieving, parsing, and validating the\
    \ \nvarious portions of a web harvesting workflow.\n"
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: WillItSync
  version: 1.1.1
servers:
- description: Development server on localhost
  url: https://localhost:8080/willitsync/1.1.1
tags:
- description: Operations available to regular developers
  name: developers
- description: Operation available to all users
  name: users
paths:
  /robots:
    get:
      description: |
        Given a robots.txt file, parse, and retrieve referenced sitemap locations.
      operationId: parse_robots
      parameters:
      - description: URL pointing to a robots.txt file
        example: https://my.server.org/robots.txt
        explode: true
        in: query
        name: url
        required: true
        schema:
          format: url
          type: string
        style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RobotsFile'
          description: Parsed robots.txt file
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RobotsFile'
          description: bad input parameter
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RobotsFile'
          description: No robots.txt file found
      summary: Retrieve sitemap references from a robots.txt file
      tags:
      - developers
      - users
      x-openapi-router-controller: openapi_server.controllers.developers_controller
  /scivalid:
    get:
      description: |
        Given a URL referencing an XML metadata document, retrieve and
        validate the XML.
      operationId: get_validate_metadata
      parameters:
      - description: "URL referencing a science metadata XML document to retrieve\
          \ \nand validate.\n"
        example: https://my.server/metadata/iso_metadata.xml
        explode: true
        in: query
        name: url
        required: true
        schema:
          format: url
          type: string
        style: form
      - description: |
          The DataONE formatId of the XML to test for validity.
        example: http://www.isotc211.org/2005/gmd
        explode: true
        in: query
        name: formatid
        required: true
        schema:
          type: string
        style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SCIMetadata'
          description: "Metadata successfully parsed and validated. The response body\
            \ \ncontains the retrieved XML metadata.\n"
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SCIMetadata'
          description: Bad input parameter
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SCIMetadata'
          description: No XML document found at URL
      summary: Retrieve and validate a science metadata XML document
      tags:
      - developers
      - users
      x-openapi-router-controller: openapi_server.controllers.developers_controller
    post:
      description: |
        Given an XML metadata document, validate the XML.
      operationId: validate_metadata
      parameters:
      - description: |
          The DataONE formatId of the XML to test for validity.
        example: http://www.isotc211.org/2005/gmd
        explode: true
        in: query
        name: formatid
        required: true
        schema:
          type: string
        style: form
      requestBody:
        content:
          text/xml:
            schema:
              format: xml
              type: string
          application/xml:
            schema:
              format: xml
              type: string
        description: |
          Science metadata XML document to validate.
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SCIMetadata'
          description: |
            JSON-LD successfully parsed and validated. The response body contains the
            retrieved schema.org JSON-LD object in the metadata element.
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SCIMetadata'
          description: Bad input parameter
      summary: Validate provided science metadata XML document
      tags:
      - developers
      - users
      x-openapi-router-controller: openapi_server.controllers.developers_controller
  /sitemap:
    get:
      description: |
        Parses a sitemap to retrieve location entries.
      operationId: parse_sitemap
      parameters:
      - description: URL pointing to a sitemap xml document
        example: https://my.server.org/sitemap.xml
        explode: true
        in: query
        name: url
        required: true
        schema:
          format: url
          type: string
        style: form
      - description: |
          Maximum number of sitemap locations to return
        explode: true
        in: query
        name: maxlocs
        required: false
        schema:
          default: 100
          type: integer
        style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sitemap'
          description: Sitemap successfully retrieved and parsed
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sitemap'
          description: Bad input parameter
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sitemap'
          description: No sitemap document found at url
      summary: Get locatiosn from a sitemap.
      tags:
      - developers
      - users
      x-openapi-router-controller: openapi_server.controllers.developers_controller
  /so:
    get:
      description: |
        Parses landing page to extract schema.org JSON-LD metadata
      operationId: parse_landingpage
      parameters:
      - description: |
          URL pointing to langing page to be parsed
        example: https://my.server.org/data/dataset_1
        explode: true
        in: query
        name: url
        required: true
        schema:
          format: url
          type: string
        style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SOMetadata'
          description: Landing page successfully retrieved and parsed
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SOMetadata'
          description: Bad input parameter
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SOMetadata'
          description: No landing page document found at URL
      summary: Extract schema.org metadata from web page
      tags:
      - developers
      - users
      x-openapi-router-controller: openapi_server.controllers.developers_controller
  /sovalid:
    get:
      description: "Given a URL referencing a schema.org JSON-LD document, verify\
        \ that \nthe structure matches expected model indicated in the type parameter.\n"
      operationId: get_validate_so
      parameters:
      - description: |
          URL referencing a schema.org JSON-LD document or a landing page containing schema.org JSON-LD to retrieve and validate.
        example: https://my.server.net/data/dataset_1/jsonld.json
        explode: true
        in: query
        name: url
        required: true
        schema:
          format: url
          type: string
        style: form
      - description: |
          The name of the schema.org type to test for validity.
        example: Dataset
        explode: true
        in: query
        name: sotype
        required: false
        schema:
          default: Dataset
          type: string
        style: form
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SOMetadata'
          description: |
            JSON-LD successfully parsed and validated. The response body contains the retrieved schema.org JSON-LD object in the metadata element.
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SOMetadata'
          description: Bad input parameter
        404:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SOMetadata'
          description: No JSON-LD document found at URL
      summary: Retrieve and validate a schema.org JSON-LD document
      tags:
      - developers
      - users
      x-openapi-router-controller: openapi_server.controllers.developers_controller
    post:
      description: "Given a schema.org JSON-LD document, verify that the structure\
        \ \nmatches expected model indicated in the type parameter.\n"
      operationId: validate_so
      parameters:
      - description: |
          The name of the schema.org type to test for validity.
        explode: true
        in: query
        name: type
        required: false
        schema:
          default: Dataset
          type: string
        style: form
      requestBody:
        content:
          application/json:
            schema:
              type: object
        description: |
          Schema.org JSON-LD to validate.
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SOMetadata'
          description: |
            JSON-LD successfully parsed and validated. The response body contains the
            retrieved schema.org JSON-LD object in the metadata element.
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SOMetadata'
          description: Bad input parameter
      summary: Validate provided schema.org JSON-LD document
      tags:
      - developers
      - users
      x-openapi-router-controller: openapi_server.controllers.developers_controller
components:
  schemas:
    RobotsFile:
      example:
        log:
        - msg: A debug message
          level: 10
          timestamp: 2016-08-29T09:12:33.001Z
        - msg: A debug message
          level: 10
          timestamp: 2016-08-29T09:12:33.001Z
        sitemaps:
        - https://my.server.com/test/sitemap.xml
        - https://my.server.com/test/sitemap.xml
        evaluated_date: 2000-01-23T04:56:07.000+00:00
        url: https://my.server.org/test
      properties:
        url:
          description: The URL for the robots.txt file
          example: https://my.server.org/test
          format: url
          type: string
        log:
          items:
            $ref: '#/components/schemas/LogEntry'
          type: array
        evaluated_date:
          description: |
            The time stamp for when the evaluation of robots.txt
            was initiated.
          format: date-time
          type: string
        sitemaps:
          description: |
            A list of sitemap URLs retrieved from the robots.txt file
          items:
            example: https://my.server.com/test/sitemap.xml
            format: url
            type: string
          type: array
      required:
      - evaluated_date
      - log
      - sitemaps
      - url
      type: object
    Sitemap:
      example:
        urlset:
        - url: http://example.com/aeiou
          lastmod: 2000-01-23T04:56:07.000+00:00
        - url: http://example.com/aeiou
          lastmod: 2000-01-23T04:56:07.000+00:00
        log:
        - msg: A debug message
          level: 10
          timestamp: 2016-08-29T09:12:33.001Z
        - msg: A debug message
          level: 10
          timestamp: 2016-08-29T09:12:33.001Z
        sitemaps:
        - https://my.server.net/test/sitemap.xml
        - https://my.server.net/test/sitemap.xml
        evaluated_date: 2000-01-23T04:56:07.000+00:00
      properties:
        sitemaps:
          description: |
            List of sitemap URLs that were examined. The zeroth item
            is always the URL provided in the request.
          items:
            description: |
              URL for a sitemaps.xml file that was examined.
            example: https://my.server.net/test/sitemap.xml
            format: url
            type: string
          type: array
        evaluated_date:
          description: |
            The timestamp for when the evaluation of sitemaps.xml
            was initiated.
          format: date-time
          type: string
        log:
          items:
            $ref: '#/components/schemas/LogEntry'
          type: array
        urlset:
          description: |
            A list of location entries retieved from the sitemap. Includes
            locations obtained from referenced sitemaps, if any.
          items:
            $ref: '#/components/schemas/Sitemap_urlset'
          type: array
      required:
      - evaluated_date
      - log
      - sitemaps
      - urlset
    SOMetadata:
      example:
        metadata: '{}'
        log:
        - msg: A debug message
          level: 10
          timestamp: 2016-08-29T09:12:33.001Z
        - msg: A debug message
          level: 10
          timestamp: 2016-08-29T09:12:33.001Z
        evaluated_date: 2000-01-23T04:56:07.000+00:00
        url: http://example.com/aeiou
      properties:
        url:
          description: |
            URL of the content that was parsed. If a redirection
            occurs, then this is the final URL that was used to
            retrieve the content.
          format: url
          type: string
        evaluated_date:
          description: |
            The timestamp for when the evaluation the landing page
            was initiated.
          format: date-time
          type: string
        log:
          items:
            $ref: '#/components/schemas/LogEntry'
          type: array
        metadata:
          description: |
            The schema.org metadata that was retrieved.
          type: object
      required:
      - evaluated_date
      - log
      - metadata
      - url
    SCIMetadata:
      example:
        metadata: metadata
        log:
        - msg: A debug message
          level: 10
          timestamp: 2016-08-29T09:12:33.001Z
        - msg: A debug message
          level: 10
          timestamp: 2016-08-29T09:12:33.001Z
        evaluated_date: 2000-01-23T04:56:07.000+00:00
        url: http://example.com/aeiou
      properties:
        url:
          description: "URL of the XML document that was retrieved and processed.\
            \ If a \nredirection occurs, then this is the final URL that was used\
            \ to\nretrieve the document.\n"
          format: url
          type: string
        evaluated_date:
          description: |
            The timestamp for when the evaluation the landing page
            was initiated.
          format: date-time
          type: string
        log:
          items:
            $ref: '#/components/schemas/LogEntry'
          type: array
        metadata:
          description: |
            The XML metadata document that was validated.
          format: xml
          type: string
      required:
      - evaluated_date
      - log
      - metadata
      - url
    Log:
      items:
        $ref: '#/components/schemas/LogEntry'
      type: array
    LogEntry:
      example:
        msg: A debug message
        level: 10
        timestamp: 2016-08-29T09:12:33.001Z
      properties:
        level:
          description: |
            Logging level for entry. DEBUG=10, INFO=20, WARNING=30,
            ERROR=40, FATAL=50
          example: 10
          type: integer
        timestamp:
          description: Timestamp for log entry
          example: 2016-08-29T09:12:33.001Z
          format: date-time
          type: string
        msg:
          description: The logged message.
          example: A debug message
          type: string
      required:
      - level
      - msg
      - timestamp
      type: object
    Sitemap_urlset:
      description: |
        A list of <loc> entries found in the sitemap.
      example:
        url: http://example.com/aeiou
        lastmod: 2000-01-23T04:56:07.000+00:00
      properties:
        url:
          description: |
            The value of the URL element of a loc entry in a sitemap.
          format: url
          type: string
        lastmod:
          description: |
            The value of the lastmod element of the loc entry.
          format: date-time
          type: string
